config/routes.rb
Rails.application.routes.draw do

  resources :users, except: [:index]

  resources :subs, except: [:destroy]

  resource :session, only: [:new, :create, :destroy]

  resources :posts, except: [:index] do
    resources :comments, only: [:new]

    member do
      post "upvote"
      post "downvote"
    end

  end

  resources :comments, only: [:create, :show, :destroy] do
    member do
      post "upvote"
      post "downvote"
    end
  end
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :content, :post, :author, presence: true

  belongs_to :post

  belongs_to(
    :author,
    class_name: 'User',
    foreign_key: :author_id
  )

  has_many :votes, as: :votable

  has_many(
    :child_comments,
    class_name: "Comment",
    foreign_key: :parent_comment_id
  )

  def count_votes(type)
    bool = (type == :upvote ? true : false)
    votes.where(upvote: bool).length
  end

  def score
    count_votes(:upvote) - count_votes(:downvote)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new

    render :new
  end

  def create
    comment = Comment.new(comment_params)
    comment.author = current_user

    comment.save

    redirect_to post_url(comment.post)
  end

  def show
    @comment = Comment.find(params[:id])
    render :show
  end

  def destroy
    comment = Comment.find(params[:id])

    comment.destroy

    redirect_to post_url(comment.post)
  end

  def upvote
    vote = Vote.new(user_id: current_user.id)
    comment = Comment.find(params[:id])
    vote.votable = comment
    vote.save

    redirect_to post_url(comment.post)
  end

  def downvote
    vote = Vote.new(user_id: current_user.id, upvote: false)
    comment = Comment.find(params[:id])
    vote.votable = comment
    vote.save

    redirect_to post_url(comment.post)
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id, :parent_comment_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<p><%= c1.content %> <br>
By <%= c1.author.username %><br>
Created at <%= c1.created_at %><br>
<a href='<%= comment_url(c1) %>'>Go to comment</a><br>
Score: <%= c1.score %>
</p>
<% ["upvote", "downvote"].each do |vote| %>
  <form action="<%= send("#{vote}_comment_url", c1) %>" method="POST">
    <%= auth_token %>
    <button><%= vote.upcase %></button>
  </form>
<% end %>

<ul>
  <% parents[c1.id].sort_by(&:score).reverse.each do |c2| %>
    <%= render("comments/comment", c1: c2, parents: parents)  %>
  <% end %>
</ul>

app/views/comments/show.html.erb
<p><%= @comment.content %> <br>
By <%= @comment.author.username %><br>
</p>
<br>

Write a new comment:
<form action="<%= comments_url %>" method="POST">
  <%= auth_token %>
  <input type='hidden' name='comment[parent_comment_id]' value='<%= @comment.id %>'>
  <input type='hidden' name='comment[post_id]' value='<%= @comment.post_id %>'>
  <textarea name="comment[content]"></textarea>
  <br>
  <button>Create!</button>
</form>