config/routes.rb
Rails.application.routes.draw do

  resources :users, except: [:index]

  resources :subs, except: [:destroy]

  resource :session, only: [:new, :create, :destroy]

  resources :posts, except: [:index] do
    resources :comments, only: [:new]

    member do
      post "upvote"
      post "downvote"
    end

  end

  resources :comments, only: [:create, :show, :destroy] do
    member do
      post "upvote"
      post "downvote"
    end
  end
  
end

app/models/sub.rb
class Sub < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: [:finders]

  validates :title, :moderator, presence: true

  belongs_to(
    :moderator,
    class_name: 'User',
    foreign_key: :moderator_id
  )

  has_many :post_subs

  has_many(
    :posts,
    through: :post_subs
  )

end

app/controllers/subs_controller.rb
class SubsController < ApplicationController

  before_action :ensure_logged_in
  before_action :non_mods_cant_edit_subs, only: [:edit, :update]

  def new
    @sub = Sub.new
    render :new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator = current_user

    if @sub.save
      flash[:notice] = ["Welcome #{@sub.title}!"]
      redirect_to @sub
    else
      flash[:failure] = @sub.errors.full_messages
      render :new
    end
  end

  def show
    @sub = Sub.find(params[:id])
    @posts = @sub.posts.page(params[:page]).per(2)
    render :show
  end

  def edit
    @sub = Sub.find(params[:id])

    render :edit
  end

  def update
    @sub = Sub.find(params[:id])

    if @sub.update_attributes(sub_params)
      flash[:notice] = ["Sub successfully updated!"]
      redirect_to @sub
    else
      flash[:failure] = @sub.errors.full_messages
      render :edit
    end
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description, :moderator_id)
  end

  def ensure_logged_in
    unless logged_in?
      redirect_to new_session_url
    end
  end

  def non_mods_cant_edit_subs
    sub = Sub.find(params[:id])
    unless current_user == sub.moderator
      redirect_to sub
    end
  end

end

app/helpers/subs_helper.rb
module SubsHelper
end

app/views/subs/_form.html.erb
<% action_url = ( action == :new ? subs_url : sub_url(sub) ) %>
<% method = ( action == :new ? "POST" : "PATCH") %>

<h1><%= header %></h1>

<form action='<%= action_url %>' method="POST">
  <input type='hidden' name='_method' value='<%= method %>'>
  <%= auth_token %>

  <label for='title'>Sub title:</label>
  <input type='text' name='sub[title]' value='<%= sub.title %>'>
  <br>

  <label for='description'>Description:</label>
  <textarea id='description' name='sub[description]'><%= sub.description %></textarea>
  <br>

  <button>Submit</button>
</form>

app/views/subs/edit.html.erb
<%= render "form", sub: @sub, header: "Edit sub-forum details", action: :edit %>

app/views/subs/new.html.erb
<%= render "form", sub: @sub, header: "Make a new sub-forum", action: :new %>

app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>
<h3><%= @sub.description %></h3>

<% if @sub.moderator == current_user %>
  <a href="<%= edit_sub_url %>">Edit sub</a>
<% end %>

<a href='<%= new_post_url %>'>Create a new post</a>
<br>

<ul>
<% @posts.each do |post| %>
  <li><a href='<%= post_url(post) %>'><%= post.title %></a></li>
  <li>Score: <%= post.score %></li>
  <% ["upvote", "downvote"].each do |vote| %>
    <form action="<%= send("#{vote}_post_url", post) %>" method="POST">
      <%= auth_token %>
      <input type="hidden" name="sub[id]" value="<%= @sub.id %>">
      <button><%= vote.upcase %></button>
    </form>
  <% end %>
<% end %>
</ul>

<%= paginate @posts %>
<%= page_entries_info @posts %>