config/routes.rb
Rails.application.routes.draw do

  resources :users, except: [:index]

  resources :subs, except: [:destroy]

  resource :session, only: [:new, :create, :destroy]

  resources :posts, except: [:index] do
    resources :comments, only: [:new]

    member do
      post "upvote"
      post "downvote"
    end

  end

  resources :comments, only: [:create, :show, :destroy] do
    member do
      post "upvote"
      post "downvote"
    end
  end
  
end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: [:finders]

  validates :title, :author, presence: true
  validates :subs, length: { minimum: 1 }


  has_many :comments
  has_many :votes, as: :votable

  has_many(
    :post_subs
  )

  has_many(
    :subs,
    through: :post_subs
  )

  belongs_to(
    :author,
    class_name: 'User',
    foreign_key: :author_id
  )

  def comments_by_parent_id
    # comments.inject(Hash.new { [] }) { |acc, c| acc[c.parent_comment_id] + [c] }
    result = Hash.new { [] }

    comments.each { |comment| result[comment.parent_comment_id] += [comment] }

    result
  end

  def count_votes(type)
    bool = (type == :upvote ? true : false)
    votes.where(upvote: bool).length
  end

  def score
    count_votes(:upvote) - count_votes(:downvote)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :ensure_logged_in
  before_action :non_authors_cant_edit_post, only: [:edit, :update]

  def new
    @post = Post.new
    @subs = Sub.all
    render :new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user

    if @post.save
      flash[:notice] = ["Post created successfully!"]
      redirect_to post_url(@post)
    else
      flash[:failure] = @post.errors.full_messages
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @comments_by_parent_id = @post.comments_by_parent_id
    @all_comments = @post.comments
    render :show
  end

  def edit
    @post = Post.find(params[:id])
    @subs = Sub.all

    render :edit
  end

  def update
    @post = Post.find(params[:id])

    if @post.update_attributes(post_params)
      flash[:notice] = ["Post successfully updated!"]
      redirect_to post_url(@post)
    else
      flash[:failure] = @post.errors.full_messages
      render :edit
    end
  end

  def upvote
    vote = Vote.new(user_id: current_user.id)
    post = Post.find(params[:id])
    vote.votable = post
    vote.save

    redirect_to sub_url(params[:sub][:id])
  end

  def downvote
    vote = Vote.new(user_id: current_user.id, upvote: false)
    post = Post.find(params[:id])
    vote.votable = post
    vote.save

    redirect_to sub_url(params[:sub][:id])
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end

  def ensure_logged_in
    unless logged_in?
      redirect_to new_session_url
    end
  end

  def non_authors_cant_edit_post
    unless current_user == Post.find(params[:id]).author
      redirect_to post_url(params[:id])
    end
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<% action_url = ( action == :new ? posts_url : post_url(post) ) %>
<% method = ( action == :new ? "POST" : "PATCH") %>

<h1><%= header %></h1>

<form action='<%= action_url %>' method="POST">
  <input type='hidden' name='_method' value='<%= method %>'>
  <%= auth_token %>

  <label for='title'>Post title:</label>
  <input type='text' name='post[title]' value='<%= post.title %>'>
  <br>

  <label>Pick sub(s):</label>
  <% subs.each do |sub| %>
  <input type='checkbox' id='<%= sub.id %>' name='post[sub_ids][]' value='<%= sub.id %>'
    <%= 'checked' if post.subs.include?(sub) %>>
  <label for='<%= sub.id %>'><%= sub.title %></label>
  <% end %>
  <br>

  <label for='description'>Content:</label>
  <textarea id='description' name='post[content]'><%= post.content %></textarea>
  <br>

  <button>Submit</button>
</form>

app/views/posts/edit.html.erb
<%= render "form", post: @post, subs: @subs, header: "Edit post details", action: :edit %>

app/views/posts/new.html.erb
<%= render "form", post: @post, subs: @subs, header: "Make a new post", action: :new %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<h3><%= @post.content %></h3>
<% if @post.author == current_user %>
  <a href="<%= edit_post_url %>">Edit post</a>
<% end %>

<br>
<br>

Comments:<br>
<% @all_comments.select { |comment| comment.parent_comment_id.nil? }
  .sort_by(&:score).reverse.each do |comment| %>
  <%= render "comments/comment", c1: comment, parents: @comments_by_parent_id %>
<% end %>

<br><br>

Write a new comment:
<form action="<%= comments_url %>" method="POST">
  <%= auth_token %>
  <input type='hidden' name='comment[post_id]' value='<%= @post.id %>'>
  <textarea name="comment[content]"></textarea>
  <br>
  <button>Create!</button>
</form>